name: Feature Request
description: Suggest a new feature or improvement for this OpenCTI deployment
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for suggesting a feature! Please complete the form below.

  - type: dropdown
    id: area
    attributes:
      label: Area
      description: Which area does this feature relate to?
      options:
        - OpenCTI Platform configuration
        - New connector integration
        - Existing connector improvement
        - Infrastructure / Docker Compose
        - Authentication / LDAP
        - Documentation
        - Other
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Is your feature request related to a problem? Describe it.
      placeholder: I find it frustrating when...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution or feature you would like to see.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Any alternative solutions or features you have considered?

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or references here.
