connector:
  id: "threatfox-connector-01"
  type: "EXTERNAL_IMPORT"
  name: "ThreatFox"
  scope: "indicator"
  confidence_level: 80
  update_existing_data: true
  log_level: "info"

opencti:
  url: "http://opencti:8080"
  token: ""  # set to OPENCTI_ADMIN_TOKEN value

threatfox:
  api_url: "https://threatfox-api.abuse.ch/api/v1/"
  import_ioc_types: "all"
  interval: 3600
